In [ ]:
Q2 Row echelon Form : Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the random matrix, 
set the random seed as the last two digits of your roll number. Reduce matrix A to its Row Echelon Form by performing elementary row operations.



In [9]:
import numpy as np

seed = 20  
np.random.seed(seed)


A = np.random.randint(0, 10, (5, 5))


print("Original Matrix A:")
print(A)
print()

A = A.astype(float)
for i in range(5):
    # Find the first nonzero entry in the current row
    pivot = np.argmax(A[i] != 0)
    if pivot == len(A):  # Skip if row is all zeros
        continue

    
    A[[i, pivot]] = A[[pivot, i]]

    
    A[i] /= A[i, i]

    for k in range(i + 1, 5):
        A[k] -= A[k, i] * A[i]


print("Row Echelon Form of Matrix A:")
print(A)


Original Matrix A:
[[3 9 4 6 7]
 [2 0 6 8 5]
 [3 0 6 6 0]
 [9 5 7 5 2]
 [6 9 3 3 9]]

Row Echelon Form of Matrix A:
[[ 1.          3.          1.33333333  2.          2.33333333]
 [-0.          1.         -0.55555556 -0.66666667 -0.05555556]
 [-0.         -0.          1.          2.          2.5       ]
 [ 0.          0.          0.          1.          3.36885246]
 [ 0.          0.          0.          0.          1.        ]]
