In [ ]:
Q3

In [1]:
import numpy as np

# Define the matrix A (use the same code for generating A as in the previous question)
np.random.seed(42)
A = np.random.randint(0, 10, (5, 5))

# Perform Singular Value Decomposition (SVD)
U, S, Vt = np.linalg.svd(A, full_matrices=False)

# Create the diagonal matrix Σ from the singular values
Sigma = np.diag(S)

# Print the matrices U, Σ, and V^T
print("Matrix U:")
print(U)
print("\nMatrix Σ:")
print(Sigma)
print("\nMatrix V^T:")
print(Vt)
print()

# Verify that A equals the product of U, Σ, and V^T
reconstructed_A = np.dot(U, np.dot(Sigma, Vt))
print("Is A equal to U * Σ * V^T?", np.allclose(A, reconstructed_A))
print()

# Find the rank 2 and rank 3 approximations of matrix A
rank_2_approx = np.dot(U[:, :2], np.dot(np.diag(S[:2]), Vt[:2, :]))
rank_3_approx = np.dot(U[:, :3], np.dot(np.diag(S[:3]), Vt[:3, :]))

print("Rank 2 Approximation of A:")
print(rank_2_approx)
print("\nRank 3 Approximation of A:")
print(rank_3_approx)


Matrix U:
[[-0.46659592  0.10065472 -0.02287376  0.32537883 -0.81594257]
 [-0.501475   -0.53162269 -0.44588159  0.35524809  0.37535123]
 [-0.39771671  0.79009347 -0.34775324 -0.11898872  0.2871987 ]
 [-0.34525211 -0.28793584 -0.11189547 -0.8675511  -0.18090999]
 [-0.50342177  0.00954962  0.81683137  0.03352891  0.27953113]]

Matrix Σ:
[[25.72194822  0.          0.          0.          0.        ]
 [ 0.          6.67758506  0.          0.          0.        ]
 [ 0.          0.          5.2344033   0.          0.        ]
 [ 0.          0.          0.          3.47436002  0.        ]
 [ 0.          0.          0.          0.          0.56664098]]

Matrix V^T:
[[-0.46266698 -0.21506951 -0.62229342 -0.40492701 -0.43413062]
 [-0.43787392  0.67111646  0.16711085 -0.46880483  0.33191132]
 [-0.45347919 -0.66990494  0.24807708 -0.07326397  0.52789596]
 [ 0.41919976 -0.00398332 -0.63173596 -0.17840305  0.62716642]
 [-0.46133922  0.23357934 -0.35240928  0.76096051  0.17132896]]

Is A equal to U *